### ISSUE TITLE
No picture in motioneye app

### ISSUE THREAD

**Issue by zslukacsik** [JairajJangle/motionEye_app_HomeSurveillanceSystem#12]
Hi,

Everything working properly but no picture in motioneye app after connected to server.
My solution: Disabling Chrome app. But after a day the motioneye not working again.
If I enable the Chrome app and manage-delete all data and disable it, the motioneye will work for one day again.
Could you give me a better solution?

Motioneye version: 0.9.7.5.2
Android version: 7.1.1

**Comment by JairajJangle** [comment]
Could you please try reinstalling motionEye from server-side. This is a strange issue that took over motionEye in the past year. Many reported that reinstalling motionEye did the trick.

If you are not even able to see the motionEye streaming from chrome app please create an issue in the server-side repo: https://github.com/ccrisan/motioneye
