### ISSUE TITLE
[Question] Data collection on/off switch?

### ISSUE THREAD

**Issue by ovz93br43v7** [JairajJangle/motionEye_app_HomeSurveillanceSystem#19]
Hello,

according to your privacy policy you collect certain log data. 
Can I as user decide whether the logs are sent or is there anywhere an on/off switch?

Thank you in advance!

**Comment by JairajJangle** [comment]
Greetings,

No user data is collected in the logs, only crash logs and App Not
Responding error logs are collected by Google Play services by default for
all apps on the Google Play Store for developers reference to fix these
issues in future updates.

These crash logs purely include source code based logs.

Unfortunately, Google does not provide a way to turn off these logs to any
apps on the Google Play Store. I assure you that these logs does not
contain any user data.

Regards,
Jairaj Jangle

**Comment by ovz93br43v7** [comment]
Thanks for your answer. That means the F-Droid version has no log reporting feature?

**Comment by JairajJangle** [comment]
Correct, and if your phone does not have Google Play services.
