### ISSUE TITLE
Connect to MotionEye server

### ISSUE THREAD

**Issue by peerchemist** [JairajJangle/motionEye_app_HomeSurveillanceSystem#20]
Hello, can this app connect to MotionEye server? Rather than adding the camera again in the mobile app, I wish to only use to watch the camera stream.

**Comment by JairajJangle** [comment]
@peerchemist 
Yes, you can connect to your motionEye server using this app. If you have already added the camera once in your motionEye server, you will not need to add it again. 

Just enter the IP address or the URL pointing to your motionEye server in the app using the "+" Add button in the bottom right corner.

For example, if your server IP address is `192.168.1.2`, assuming the default motionEye port(`8765`):
1. Enter `http://192.168.1.2:8765` in the "Device URL" text input box 
2. Alternatively, enter `http://192.168.1.2` in the Device URL text input box and `8765` in the "Port" input text box.
