### ISSUE TITLE
Download for Videos not possible since version 1.0.1

### ISSUE THREAD

**Issue by move-some** [JairajJangle/motionEye_app_HomeSurveillanceSystem#53]
Hello,

If I try to download a recorded video, the app FC's.
Since V1.0.1 the app does not ask for permission to write to the phone's storage.

2023-08-28 09:54:32.691 32622 32622 com.jairaj.janglegmail.motioneye E AndroidRuntime: java.lang.SecurityException: No permission to write to /storage/emulated/0/Download/motionEye/test_Camera1_17-53-04.avi: Neither user 10065 nor current process has android.permission.WRITE_EXTERNAL_STORAGE.

Using V0.9.7.5.4, download is possible BUT there is a":" at the end of the file extension (e.g. test_Camera1_17-53-04.avi:)

**Comment by move-some** [comment]
Additional information.
I tried version 0.9.9.2.5 and download is working.
All tests done using Android 9.

**Comment by move-some** [comment]
Sorry, didn't want to close, just pushed the wrong button

**Comment by move-some** [comment]
Try to reopen

**Comment by JairajJangle** [comment]
@move-some I will investigate the issue on the weekends and maybe deploy a fix in the next week.

**Comment by move-some** [comment]
Sounds good. Currently, I am running V0.9.9.2.5 without any big issues.

**Comment by JairajJangle** [comment]
This issue was specific to Android < 11. It has been fixed, and the update is rolled out to the Play Store. Meanwhile, if you want to sideload the latest version, check the release page: https://github.com/JairajJangle/motionEye_app_HomeSurveillanceSystem/releases/tag/v1.0.4

**Comment by move-some** [comment]
Just tried version 1.0.4 and it is working for me.
Thanks a lot.
