### ISSUE TITLE
Device URL with IPv6 addresses are detected as invalid

### ISSUE THREAD

**Issue by TheDidek** [JairajJangle/motionEye_app_HomeSurveillanceSystem#55]
Adding a server with a valid IPv6 URL address like "http://[fe80::a709:de4a:5817:b329]" throws an "Invalid URL" error.

Temporary workaround: Use a service like sslip.io to convert domain name directly to IP address.

**Comment by JairajJangle** [comment]
Fixed in e9b2c320a5899d79a6f7b2dd19c50562de531e68

---
Fix available in [v1.0.5](https://github.com/JairajJangle/motioneye-android/releases/tag/v1.0.5) (expected to get published by tomorrow on Play Store _[22 Feb 2024]_).

**Comment by TheDidek** [comment]
Fast! Thank you very much.
