### ISSUE TITLE
"media decode error or unsupported media features" when trying to watch recorded files

### ISSUE THREAD

**Issue by olskar** [JairajJangle/motionEye_app_HomeSurveillanceSystem#6]
Hello!

I get "media decode error or unsupported media features" when trying to watch recorded files. This is with eyemotion 4.0. There are nothing wrong with the files as I can watch them on my computer browser and if I download them.

**Comment by JairajJangle** [comment]
You may want to check this thread: https://github.com/ccrisan/motioneye/issues/1206 We are not able to reproduce the issue on our side, please follow the steps given in the thread and let us know, we will help you further.

**Comment by JairajJangle** [comment]
Closed, as the issue is related to the server side and not the Android app.
