### ISSUE TITLE
Alternative download source

### ISSUE THREAD

**Issue by IzzySoft** [JairajJangle/motionEye_app_HomeSurveillanceSystem#8]
Would you mind making your app available via [F-Droid](https://f-droid.org/) or at least [tagging releases](https://github.com/JairajJangle/motionEye_app_HomeSurveillanceSystem/releases) and attaching it the APK there? Looks promising, but some of us tin foils rather avoid Play Store – and other folks cannot access it. Would be great to have an alternative.

Thanks in advance!

**Comment by dadosch** [comment]
As far a I can see, there are no problems on the software side(like FCM) which would be incompatible with fdroid.

@JairajJangle you would just have to agree to have it in F-Droid and tag a new release via the github release system (https://github.com/JairajJangle/motionEye_app_HomeSurveillanceSystem/releases)

**Comment by JairajJangle** [comment]
Will be releasing soon on FDroid, maybe after an update, I am working on.

**Comment by IzzySoft** [comment]
That's great news! If you need help getting it listed with F-Droid, feel free to ping me, I gladly assist.

**Comment by JairajJangle** [comment]
Sure, thank for offering help, will let you know.

**Comment by JairajJangle** [comment]
Just to let interested ones know, due to lack of time, the release is delayed but it's definitely coming.

**Comment by IzzySoft** [comment]
@JairajJangle Uh? Did I miss something, and it was added to F-Droid using a different package name? Or did you accidentally close the wrong issue?

**Comment by JairajJangle** [comment]
Can I get all the steps to add the app to Fdroid at one place? The guide to add apps on Froid is frustratingly scattered.

**Comment by IzzySoft** [comment]
Ugh… Maybe go the easy way, and simply [open an RFP](https://gitlab.com/fdroid/rfp/issues). Simplest when taking the default template and fill in all details; I'd then take care for transforming metadata. Might ping you (there or here) for missing details if any, packagers might ping you later if they run into trouble – and all of the mentioned are thankful for your help then :smiley:

If you want to take the technical approach, you can also [open a merge request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests) with prepared metadata. But that would mean you have a copy of the F-Droid build structure and can test the build. The big pro is it would go faster, as our packagers would just need to "confirm" instead of setting up builds themselves.

I can help you with the first approach. Not being an Android dev, I cannot tell much about the second.

**Comment by JairajJangle** [comment]
Added issue: https://gitlab.com/fdroid/rfp/-/issues/1277

**Comment by IzzySoft** [comment]
Thanks, great! Question ahead (while we wait for the bot scan results): Mind to implement [Fastlane file structure](https://gitlab.com/snippets/1895688) here in your repo? That way you can maintain summary/description (as well as provide screenshots), and F-Droid would pick them up automatically. When you do this, please cover them by a tag afterwards (Fastlane is always picked up from the same tag the app was built from).

**Comment by IzzySoft** [comment]
Ugh, bot was fast and already approved :+1:

PS: The "insecure gradle" affects *your* builds, so it's no show-stopper for the RFP (you still will want to fix it, though).

**Comment by IzzySoft** [comment]
"Fastlane starter kit" – just extract to the root of your repo :wink:

[com.jairaj.janglegmail.motioneye_fastlane.zip](https://github.com/JairajJangle/motionEye_app_HomeSurveillanceSystem/files/4398854/com.jairaj.janglegmail.motioneye_fastlane.zip)

**Comment by JairajJangle** [comment]
Added fastlane to the root @IzzySoft

**Comment by IzzySoft** [comment]
Cool, thanks! Now can you cover that by a tag? Then I could push the RFP "upstairs".

**Comment by JairajJangle** [comment]
Done, release at [v0.9.8.0.1_FDroid](https://github.com/JairajJangle/motionEye_app_HomeSurveillanceSystem/releases/tag/v0.9.8.0.1_FDroid_prod)

**Comment by IzzySoft** [comment]
Ahem… Sorry, that causes an issue: Unless you plan to always use the `_FDroid` suffix for F-Droid releases and want F-Droid to pick up only those, it shouldn't be there. Reason is that for autmated updates, we define a pattern what tags to look for – which for your other tags would be `v%v` (versionCode, prefixed by a "v") – which wouldn't see this tag. Making that `v%v_FDroid` would make it miss all other tags…

Options would be making that `v0.9.8.0.2` – or "moving up" `v0.9.8.0.1` to that commit.

**Comment by JairajJangle** [comment]
New release [v0.9.8.0.1](https://github.com/JairajJangle/motionEye_app_HomeSurveillanceSystem/releases/tag/v0.9.8.0.1)

**Comment by IzzySoft** [comment]
Thanks! Updated the RFP: removed summary/desc from metadata, added fastlane+ready labels. :crossed_fingers:

**Comment by JairajJangle** [comment]
@IzzySoft any updates on the FDroid release?

**Comment by IzzySoft** [comment]
See there (at the RFP). Sorry, I'm no packager, so it doesn't help pinging me here (if you ping on the RFP, there's at least a chance a packager gets aware of it – here the chance for that is much lower). I've marked it ready for packaging, which is where my terrain ends.
